<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkLinkService.Domain\WorkLinkService.Domain.csproj" />
    <ProjectReference Include="..\WorkLinkService.ValueObjects\WorkLinkService.ValueObjects.csproj" />
  </ItemGroup>

</Project>
